// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7mKPV5EQAn3WkGLz889MWtYy5mN4_PP4',
    appId: '1:104327291109:web:eb48d4e1d77faf34f4340c',
    messagingSenderId: '104327291109',
    projectId: 'pet-shop-21fe1',
    authDomain: 'pet-shop-21fe1.firebaseapp.com',
    storageBucket: 'pet-shop-21fe1.appspot.com',
    measurementId: 'G-MKD5G5SNPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcn2I8oAyE0UqrTj_8nRScTijge9kaPy8',
    appId: '1:104327291109:android:f9e198cf5d02f69bf4340c',
    messagingSenderId: '104327291109',
    projectId: 'pet-shop-21fe1',
    storageBucket: 'pet-shop-21fe1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBseKTWM41GOvjhXFK1bRubkplVEoR3F1g',
    appId: '1:104327291109:ios:3647c236f07bc51cf4340c',
    messagingSenderId: '104327291109',
    projectId: 'pet-shop-21fe1',
    storageBucket: 'pet-shop-21fe1.appspot.com',
    iosBundleId: 'com.chinrust.pet4u',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBseKTWM41GOvjhXFK1bRubkplVEoR3F1g',
    appId: '1:104327291109:ios:4e40054b4e5e138cf4340c',
    messagingSenderId: '104327291109',
    projectId: 'pet-shop-21fe1',
    storageBucket: 'pet-shop-21fe1.appspot.com',
    iosBundleId: 'com.chinrust.pet4u.RunnerTests',
  );
}
